name: amap_core_fluttify
description: An `Amap Core` Map Component, Powered By `Fluttify`, A Compiler Generating Dart Bindings For Native SDK.
version: 0.17.0
homepage: https://github.com/fluttify-project

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  
  
  foundation_fluttify:
    git:
      url: https://github.com/banyungong/flutter_amap.git
      path: amap/foundation_fluttify
  core_location_fluttify:
    git:
      url: https://github.com/banyungong/flutter_amap.git
      path: amap/core_location_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_core_fluttify
        pluginClass: AmapCoreFluttifyPlugin
      ios:
        pluginClass: AmapCoreFluttifyPlugin